<a href="https://colab.research.google.com/github/Mutasar/Proyek_Analisis_Sentimen/blob/main/Analisa_Sentimen_Ulasan_Aplikasi_Tokopedia_di_Playstore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import dataset yang telah dilakukan text preprocessing

In [95]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from google.colab import drive
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
import joblib
from google.colab import files

# 1. inisialisasi dataset

In [75]:
# inisialisasi dataset
file_id = '1GLyhzyN3XNgmC3ftv4Klmvtlt_Dc7XzD'
download_url = f'https://drive.google.com/uc?id={file_id}'

# Membaca CSV
df = pd.read_csv(download_url)

In [76]:
df.head()

,userName,score,at,content
0,Pengguna Google,5,2024-09-08 03:31:50,makasih toped
1,Pengguna Google,1,2024-09-08 03:29:56,Aplikasi php sudah banyak dikasih promo &sudah...
2,Pengguna Google,5,2024-09-08 03:26:38,mantab... 👍
3,Pengguna Google,5,2024-09-08 03:25:14,Good good
4,Pengguna Google,1,2024-09-08 03:24:01,Sangat buruk sebagai pengguna lama akun affali...

In [78]:
# Tinjau jumlah baris kolom dan jenis data dalam dataset dengan info.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   userName  500000 non-null  object
 1   score     500000 non-null  int64
 2   at        500000 non-null  object
 3   content   499999 non-null  object
 4   label     500000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 19.1+ MB

In [79]:
# Menampilkan statistik deskriptif dataset dengan menjalankan describe

df.describe()

               score          label
count  500000.000000  500000.000000
mean        4.074004       0.759270
std         1.545313       0.427527
min         1.000000       0.000000
25%         4.000000       1.000000
50%         5.000000       1.000000
75%         5.000000       1.000000
max         5.000000       1.000000

In [91]:
df = df.rename(columns={
    'userName': 'nama',
    'score': 'rating',
    'at': 'waktu',
    'content': 'ulasan'
})
print(df.columns)

Index(['nama', 'rating', 'waktu', 'ulasan', 'label'], dtype='object')

In [92]:
df.head()

,nama,rating,waktu,ulasan,label
0,Pengguna Google,5,2024-09-08 03:31:50,makasih toped,1
1,Pengguna Google,1,2024-09-08 03:29:56,Aplikasi php sudah banyak dikasih promo &sudah...,0
2,Pengguna Google,5,2024-09-08 03:26:38,mantab... 👍,1
3,Pengguna Google,5,2024-09-08 03:25:14,Good good,1
4,Pengguna Google,1,2024-09-08 03:24:01,Sangat buruk sebagai pengguna lama akun affali...,0

# 2. Cleaning Data

In [111]:
# Mengecek dataset menggunakan isnull().sum()

print("Cek nilai null:\n", df.isnull().sum())

Cek nilai null:
 nama      0
rating    0
waktu     0
ulasan    0
label     0
dtype: int64

In [83]:
# Mengecek dataset menggunakan duplicated().sum()

print("\nJumlah duplikasi:", df.duplicated().sum())

Jumlah duplikasi: 10

In [84]:
#menghilangkan data duplikat
df = df.drop_duplicates()

In [85]:
#cek hasil drop duplikat
print("\nJumlah duplikasi:", df.duplicated().sum())

Jumlah duplikasi: 0

In [99]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [107]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [108]:
# Fungsi pembersihan teks
def clean_text(text):
    if pd.isnull(text):  # Tangani NaN
        return ""
    text = text.lower()  # Ubah ke huruf kecil
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)  # Hapus URL
    text = re.sub(r'[^a-z\s]', '', text)  # Hapus karakter non-abjad
    tokens = word_tokenize(text)  # Tokenisasi
    stop_words = set(stopwords.words('indonesian'))  # Ubah ke bahasa Indonesia jika perlu
    tokens = [word for word in tokens if word not in stop_words]  # Hapus stopwords
    return ' '.join(tokens)

# Terapkan ke kolom teks (misalnya 'ulasan')
df['ulasan'] = df['ulasan'].apply(clean_text)

In [109]:
# Tampilkan beberapa baris pertama dari kolom 'ulasan' setelah pembersihan
print("\nHasil pembersihan teks:")
print(df['ulasan'].head())

Hasil pembersihan teks:
0                                        makasih toped
1    aplikasi php dikasih promo dibayar diklik diba...
2                                               mantab
3                                            good good
4    buruk pengguna akun affalite blokir rugikan share
Name: ulasan, dtype: object

# Labeling

Pembagian data menjadi data sentimen berlabel positif dan negatif dengan angka 1 untuk positif dan angka 0 untuk negatif. Pengklasifikasian ini dilakukan pada ulasan yang memiliki rating 4 dan 5 sebagai sentimen positif dan rating 3 sampai 1 sebagai sentimen negatif.

In [119]:
# sentimen berdasarkan rating
def get_sentiment_label(rating):
    if rating >= 4:
        return 1  # Positif
    elif rating <= 3:
        return 0  # Negatif
    else:
        return None  # Jika rating tidak valid

# menerapkan fungsi ke DataFrame
df['label'] = df['rating'].apply(get_sentiment_label)

print(df.head())

              nama  rating                waktu  \
0  Pengguna Google       5  2024-09-08 03:31:50
1  Pengguna Google       1  2024-09-08 03:29:56
2  Pengguna Google       5  2024-09-08 03:26:38
3  Pengguna Google       5  2024-09-08 03:25:14
4  Pengguna Google       1  2024-09-08 03:24:01

                                              ulasan  label  label_sentimen
0                                      makasih toped      1               1
1  aplikasi php dikasih promo dibayar diklik diba...      0               0
2                                             mantab      1               1
3                                          good good      1               1
4  buruk pengguna akun affalite blokir rugikan share      0               0

In [120]:
df["label"].value_counts()

label
1    379625
0    120365
Name: count, dtype: int64

# Menghitung Kata Dengan TF-IDF

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [ ]:
Ulasan = df['content']

In [ ]:
Ulasan.isnull().sum()

np.int64(1)

In [ ]:
Ulasan = Ulasan.fillna('tidak ada komentar')

In [ ]:
#untuk menghitung jumlah kata yang telah di steming
cv = CountVectorizer()
term_fit = cv.fit(Ulasan)

print (len(term_fit.vocabulary_))

88203

In [ ]:
term_fit.vocabulary_ #mengurutkan berdasarkan urutab abjad kata

{'makasih': 44786,
 'toped': 80599,
 'aplikasi': 6020,
 'php': 63034,
 'sudah': 74755,
 'banyak': 8827,
 'dikasih': 20342,
 'promo': 64974,
 'dibayar': 19340,
 'tapi': 76431,
 'diklik': 20517,
 'jawabnya': 34098,
 'dibatalkan': 19296,
 'sistem': 73015,
 'tolong': 80424,
 'perbaiki': 62042,
 'kmu': 39784,
 'tokopedia': 80033,
 'mantab': 45806,
 'good': 28455,
 'sangat': 68818,
 'buruk': 14821,
 'sebagai': 69623,
 'pengguna': 61383,
 'lama': 42024,
 'akun': 4119,
 'affalite': 3415,
 'di': 18946,
 'blokir': 12984,
 'tanpa': 76380,
 'sebab': 69618,
 'amat': 4694,
 'rugikan': 67866,
 'dalam': 17778,
 'hal': 29967,
 'share': 72151,
 'apa': 5676,
 'harus': 30401,
 'verifikasi': 83525,
 'nomor': 56019,
 'hp': 31544,
 'gabisa': 26565,
 'dipake': 21091,
 'beberapa': 9632,
 'udah': 82149,
 'tau': 76581,
 'ribet': 67268,
 'beli': 10055,
 'baru': 9113,
 'tuh': 81689,
 'payah': 59623,
 'diskonnya': 21976,
 'gokil': 28401,
 'oke': 57325,
 'hallo': 30007,
 'dipermudah': 21275,
 'lagi': 41827,
 'pembayaran': 60544,
 'menggunakan': 49602,
 'fitur': 26063,
 'cod': 16641,
 'dikarenakan': 20335,
 'cukup': 17345,
 'merepotkan': 50767,
 'jika': 34590,
 'yang': 85837,
 'lain': 41918,
 'membantu': 47960,
 'job': 34838,
 'tq': 80810,
 'yaa': 85636,
 'promonya': 65019,
 'gak': 26802,
 'guna': 29320,
 'mempermudah': 48478,
 'saya': 69213,
 'mau': 47078,
 'voucher': 83869,
 'indomaret': 32650,
 'kenapa': 37944,
 'ket': 38822,
 'waduh': 84090,
 'tujuanmu': 81702,
 'ngga': 55121,
 'ada': 3090,
 'padahal': 58700,
 'bener': 10263,
 'maaf': 44327,
 'kasih': 36324,
 'bintang': 12477,
 'dlu': 22765,
 'ya': 85634,
 'kalau': 35759,
 'bisa': 12571,
 'mantep': 46188,
 'badjingan': 7514,
 'bagus': 7734,
 'luar': 43943,
 'biasa': 12147,
 'mantaf': 45876,
 'ok': 57294,
 'kurir': 41464,
 'recomendasi': 66397,
 'kok': 39980,
 'dipilihkan': 21359,
 'idexpres': 32011,
 'bikin': 12291,
 'emosi': 24718,
 'pembeli': 60596,
 'maksudnya': 44954,
 'ped': 59839,
 'sipud': 72954,
 'itu': 33429,
 'expedisi': 25410,
 'kurirnya': 41476,
 'hibernasi': 31065,
 'digoa': 19993,
 'uda': 82144,
 'diluar': 20754,
 'tanggal': 76285,
 'estimasi': 25172,
 'datang': 18136,
 'juga': 35238,
 'paket': 58909,
 'puas': 65321,
 'dengan': 18608,
 'pelayanan': 60275,
 'tiap': 79108,
 'dapat': 17944,
 'selalu': 70570,
 'otomatis': 58419,
 'oleh': 57615,
 'mengecewakan': 49387,
 'belanja': 9955,
 'dan': 17824,
 'transaksi': 80981,
 'lbh': 42566,
 'mudah': 52824,
 'hemat': 30836,
 'waktu': 84203,
 'apasih': 5803,
 'ga': 26494,
 'jelas': 34269,
 'banget': 8451,
 'tiba': 79121,
 'pesanan': 62824,
 'cuman': 17374,
 'perkara': 62335,
 'pake': 58881,
 'diskon': 21944,
 'kocak': 39906,
 'masa': 46693,
 'tiba2': 79122,
 'gagal': 26698,
 'buat': 14439,
 'pesan': 62817,
 'barang': 8951,
 'sekali': 70312,
 'rekomen': 66668,
 'sorry': 73963,
 'rating': 66205,
 'pesen': 62869,
 'produk': 64840,
 'mulu': 53005,
 'cape': 15380,
 'gratis': 28938,
 'ongkir': 57778,
 'tertentu': 78540,
 'update': 82894,
 'status': 74457,
 'tidak': 79162,
 'dari': 18016,
 'pihak': 63095,
 'ekspedisi': 24457,
 'pilihanpun': 63191,
 'diandalkan': 19077,
 'dulu': 23779,
 'sini': 72848,
 'jadi': 33626,
 'pilihan': 63181,
 'utama': 83164,
 'sekarang': 70384,
 'lebih': 42617,
 'baik': 8053,
 'menarik': 48788,
 'cuma': 17363,
 'untuk': 82806,
 'susah': 75379,
 'suka': 74873,
 'apk': 5903,
 'ini': 32821,
 'bila': 12306,
 'melakukan': 47553,
 'beralasan': 10412,
 'gaada': 26507,
 'kembalian': 37793,
 'trs': 81429,
 'harga': 30301,
 'sma': 73442,
 'beda': 9664,
 '2rb': 1222,
 'wifi': 84748,
 'lemot': 42830,
 'masuk': 46871,
 'ke': 36682,
 'data': 18124,
 'normal2': 56111,
 'aja': 3717,
 'mohon': 52245,
 'kembalikan': 37802,
 'vitur': 83737,
 'upload': 82970,
 'video': 83645,
 'link': 43244,
 'agar': 3505,
 'kami': 35930,
 'kirim': 39392,
 'unboxing': 82572,
 'ketika': 38985,
 'kendala': 37979,
 'atau': 6903,
 'cocok': 16633,
 'retur': 67128,
 'kembali': 37790,
 'produknya': 64852,
 'nya': 56486,
 'keren': 38382,
 'pilih': 63176,
 'yg': 86119,
 'muncul': 53069,
 'bca': 9509,
 'bank': 8715,
 'pokoknya': 64050,
 'teh': 76828,
 'debest': 18392,
 'mantap': 45931,
 'hai': 29929,
 'tokped': 80267,
 'orang': 58189,
 'sering': 71598,
 'malah': 44989,
 'dapet': 17969,
 '50': 1776,
 'rb': 66255,
 'jarang': 33972,
 'mengkhianati': 49812,
 'pelanggan': 60161,
 'tetap': 78764,
 'masyallah': 46928,
 'tabarakallah': 75853,
 'memuaskan': 48580,
 'bagi': 7636,
 'murah': 53157,
 'hrg': 31580,
 '100': 152,
 'jd': 34166,
 '10rb': 263,
 'langganan': 42213,
 'komplain': 40161,
 'telat': 76927,
 'sampai': 68627,
 'hilang': 31159,
 'perjalanan': 62315,
 'parah': 59329,
 'perhatikan': 62254,
 'bngt': 13162,
 'rekomendasi': 66677,
 'klo': 39644,
 'bandingkan': 8327,
 'sama': 68501,
 'shopee': 72287,
 'jauh': 34052,
 'toko': 79878,
 'pedia': 59880,
 'terbaik': 77404,
 'batalin': 9228,
 'saldo': 68418,
 'tambah': 76137,
 'seringlah': 71610,
 'tadi': 75879,
 'sih': 72564,
 'ubah': 82094,
 'karena': 36193,
 'care': 15451,
 'menjawab': 50110,
 'pertanyaan': 62718,
 'telah': 76908,
 'disampaikan': 21680,
 'nunggu': 56390,
 'jawaban': 34084,
 'slow': 73404,
 'respon': 67018,
 'kayak': 36542,
 'pejabat': 60048,
 'negeri': 53994,
 'apalagi': 5745,
 'pas': 59434,
 'akhir': 3931,
 'sesi': 71807,
 'gk': 28129,
 'kalimat': 35839,
 'langsung': 42259,
 'akhiri': 3936,
 'seenaknya': 70034,
 'customer': 17451,
 'sayang': 69249,
 'attitude': 6970,
 'diskonya': 21998,
 'kadang': 35585,
 'setiap': 71952,
 '1bulan': 674,
 '1x': 793,
 'minusnya': 51365,
 'bayar': 9383,
 'non': 56031,
 'tokonya': 79978,
 'pengantaran': 61197,
 'rumah': 67896,
 'kurang': 41417,
 'cepat': 15887,
 'harganya': 30325,
 'mahal': 44592,
 'karna': 36236,
 'hanya': 30184,
 'gimik': 28000,
 'saja': 68301,
 'baagus': 7363,
 'blnja': 12953,
 'ganti': 27099,
 'nomer': 56000,
 'tlong': 79619,
 'biar': 12130,
 'rame': 66068,
 'lewat': 42976,
 'qris': 65793,
 'mangga': 45397,
 'memang': 47831,
 'awal': 7091,
 'digunakan': 20016,
 'memenuhi': 48264,
 'syarat': 75620,
 'perlu': 62398,
 'dilanjutkan': 20671,
 'hingga': 31211,
 'tahap': 75950,
 'malas': 45021,
 'co': 16579,
 'pembatalan': 60517,
 'sepihak': 71442,
 'seperti': 71420,
 'batalkan': 9238,
 'demi': 18572,
 'tuhan': 81690,
 'kalo': 35865,
 'vocer': 83777,
 'aku': 4079,
 'sudi': 74782,
 'penjualnya': 61756,
 'lelet': 42737,
 'niat': 55556,
 'kerja': 38465,
 'solo': 73816,
 'klaten': 39576,
 'hari': 30341,
 'belum': 10151,
 'naik': 53530,
 'motor': 52394,
 'sejam': 70241,
 'menunggu': 50320,
 'konfirmasi': 40309,
 'doang': 22848,
 'hahaha': 29866,
 'lawak': 42459,
 'mengerti': 49480,
 'namun': 53659,
 'loading': 43488,
 'lamak': 42058,
 'jaringan': 33993,
 'makanya': 44766,
 'pernah': 62490,
 'selain': 70553,
 'ulasan': 82448,
 'jualan': 35181,
 'hendak': 30862,
 'beri': 10809,
 'opsi': 58150,
 'edit': 24150,
 'pengembangan': 61287,
 'topup': 80712,
 'gopay': 28676,
 'listrik': 43307,
 'ternyata': 78219,
 'menerima': 49159,
 'tagihan': 75922,
 'kecewa': 37033,
 'berat': 10466,
 'ngasih': 54456,
 'apa2in': 5680,
 'keterangan': 38913,
 'melanggar': 47599,
 'ketentuan': 38900,
 'hadehhh': 29655,
 'paling': 59018,
 'sejak': 70238,
 'sulit': 75041,
 'tak': 76032,
 'gabungin': 26596,
 'agak': 3494,
 'males': 45050,
 'diperbaiki': 21192,
 'dong': 22981,
 'masak': 46704,
 'kalah': 35741,
 'oyen': 58587,
 'expedisinya': 25420,
 'sumpah': 75114,
 'pdahal': 59742,
 'malang': 45018,
 'blitar': 12923,
 'ituk': 33437,
 'kan': 35994,
 'dekat': 18496,
 'sarankan': 69055,
 'usah': 83078,
 'memakai': 47796,
 'jasa': 34008,
 'percaya': 62130,
 'boleh': 13452,
 'email': 24597,
 'buktinya': 14626,
 'benar': 10202,
 'online': 57915,
 'terburuk': 77532,
 'terpercaya': 78342,
 'pengiriman': 61474,
 'masih': 46770,
 'sedang': 69903,
 'dikirim': 20481,
 'terjadi': 77922,
 'pada': 58690,
 'tracking': 80835,
 'segera': 70100,
 'bug': 14517,
 'program': 64923,
 'disediakan': 21793,
 'instal': 32973,
 'menikmati': 50006,
 'potongan': 64335,
 'zonk': 86685,
 'udh': 82192,
 'metode': 50946,
 '0vo': 148,
 'terus': 78624,
 'lazada': 42534,
 'feel': 25804,
 'very': 83585,
 'satisfied': 69129,
 'this': 79019,
 'time': 79288,
 'for': 26212,
 'sure': 75316,
 'the': 78962,
 'best': 11722,
 'konsumen': 40404,
 'toopers': 80571,
 'terbaru': 77460,
 'dimana': 20798,
 'design': 18734,
 'friendly': 26359,
 'masukan': 46876,
 'sebaiknya': 69644,
 'sederhana': 69939,
 'menjadi': 50068,
 'nilai': 55670,
 'aneh': 5123,
 'dibatalin': 19287,
 'emang': 24614,
 'enggak': 24845,
 'ush': 83128,
 'kenpaa': 38029,
 'pakai': 58844,
 'abis': 2915,
 'vocher': 83796,
 'hangus': 30140,
 'harusnya': 30416,
 'vochernya': 83800,
 'balik': 8233,
 'lah': 41877,
 'belom': 10131,
 'kepakai': 38095,
 'jadinya': 33654,
 'skarang': 73157,
 'asik': 6581,
 'melek': 47672,
 'smpe': 73562,
 'jam': 33814,
 '12': 339,
 'nungguin': 56396,
 'trnyata': 81351,
 'klaim': 39549,
 'kerennn': 38400,
 'lopyu': 43748,
 'gg': 27762,
 'gw': 29459,
 'headset': 30616,
 'bluetooth': 13033,
 'pasan': 59443,
 'comang': 16746,
 '200': 807,
 'perak': 61973,
 'bjirr': 12713,
 'onlen': 57896,
 'busuk': 14898,
 'dablek': 17616,
 'gaguna': 26729,
 'terimakasih': 77806,
 'nggak': 55134,
 'plus': 63718,
 'dipakai': 21084,
 'gitu': 28076,
 'caranya': 15434,
 'rugi': 67851,
 'kita': 39444,
 'ngapain': 54409,
 'ujung': 82357,
 'ujungnya': 82368,
 'konsisten': 40381,
 'punya': 65529,
 'berapapun': 10455,
 'gunakan': 29339,
 'gini': 28022,
 'makin': 44871,
 'love': 43792,
 'yey': 86102,
 'la': 41721,
 'mantabb': 45807,
 'mesen': 50890,
 'bang': 8348,
 'terosss': 78270,
 'katanya': 36434,
 'snk': 73665,
 'apa2': 5678,
 'dijelasin': 20271,
 'dilanggar': 20666,
 'dasar': 18069,
 'jelek': 34327,
 'complicated': 16843,
 'refund': 66534,
 'dana': 17825,
 'tertahan': 78517,
 'sekelas': 70436,
 'menahan': 48714,
 'tolol': 80402,
 'admin': 3268,
 'auto': 7037,
 'reject': 66592,
 'terima': 77776,
 'atas': 6890,
 'kupon': 41387,
 'mending': 49011,
 'ditoko': 22407,
 'sebelah': 69705,
 'deh': 18480,
 'mantappppppl': 46044,
 'okay': 57308,
 'menyenangkan': 50507,
 'mantul': 46334,
 'perbanyak': 62066,
 'insyaallah': 33040,
 'saing': 68289,
 'tambahkan': 76159,
 'paylater': 59657,
 'pdhl': 59764,
 'jdi': 34172,
 'krna': 40948,
 'ngundang': 55485,
 'teman': 77024,
 'id': 31972,
 'express': 25459,
 'paketnya': 58926,
 'jasper': 34019,
 'jaspernya': 34020,
 'kyak': 41668,
 'banyakin': 8843,
 'tertarik': 78532,
 'terbaikkk': 77407,
 'pesenan': 62874,
 'bermasalah': 11189,
 'proses': 65105,
 'minggu': 51258,
 'selesai': 70682,
 'tahan': 75946,
 'tanya': 76402,
 'jawabannya': 34087,
 'investigasi': 33166,
 'kereeen': 38355,
 'mudah2an': 52826,
 'amanah': 4656,
 'berikan': 10821,
 'ngak': 54285,
 'berguna': 10744,
 'disini': 21896,
 'stok': 74546,
 'setelah': 71909,
 'chat': 16116,
 'cs': 17213,
 'jawabnnya': 34097,
 'template': 77098,
 'bergunaa': 10745,
 'jangan': 33905,
 'intals': 33056,
 'gaes': 26679,
 'banyakk': 8848,
 'cekout': 15777,
 'gausah': 27306,
 'sok': 73784,
 'gue': 29267,
 'besarin': 11665,
 'gpp': 28847,
 'yha': 86161,
 'jne': 34804,
 'nyampainya': 56594,
 'klw': 39692,
 'alamatnya': 4224,
 'jual': 35178,
 'bebas': 9596,
 'mantull': 46347,
 'gangguan': 27055,
 'versi': 83565,
 'kaga': 35633,
 'nyaman': 56556,
 'menu': 50275,
 'ikon': 32307,
 'surat': 75310,
 'pedagang': 59845,
 'bales': 8218,
 '2bulan': 1150,
 'ngestuck': 55074,
 'gilaaa': 27895,
 'besar': 11653,
 'akses': 4018,
 'penjual': 61744,
 'solusi': 73822,
 'berhubungan': 10805,
 'uang': 82051,
 'prosesnya': 65114,
 'kereeeennnn': 38350,
 'abiss': 2924,
 'lanjutkan': 42301,
 'min': 51213,
 'ilang': 32347,
 'nyari': 56668,
 'semakin': 70819,
 'yakin': 85797,
 'sengaja': 71240,
 'nahan': 53511,
 'daftar': 17667,
 'penipu': 61662,
 'gimna': 28009,
 'biarkan': 12136,
 'berbicara': 10564,
 '50k': 1832,
 'dah': 17711,
 'effort': 24268,
 'konter': 40438,
 'mana': 45213,
 'ngepas': 54958,
 'ampe': 4890,
 'rela': 66753,
 'premium': 64606,
 'isi': 33298,
 '10k': 245,
 'taunya': 76604,
 'sitem': 73050,
 'ngendap': 54906,
 'sisa': 72982,
 'segitu': 70118,
 'kali': 35795,
 'sakit': 68342,
 'aslinya': 6633,
 'bukan': 14582,
 'masalah': 46717,
 'nominal': 56009,
 'kek': 37435,
 'ngerasa': 54972,
 'bohongin': 13382,
 'guncang': 29353,
 'berbagai': 10489,
 'prodak': 64825,
 'ter': 77259,
 'bodoh': 13333,
 'bego': 9798,
 '70': 2192,
 'harinya': 30360,
 'nanya': 53746,
 'topet': 80645,
 'syrt': 75713,
 'jelaskan': 34276,
 'langgar': 42221,
 'mantappp': 46018,
 'dpt': 23378,
 'banyaj': 8826,
 'payment': 59686,
 'kolom': 40022,
 'kemana': 37731,
 'hilangnya': 31174,
 'gacorrrr': 26620,
 'dng': 22812,
 'voucer': 83855,
 'tdk': 76704,
 'bgni': 11949,
 'sm': 73440,
 'hny': 31340,
 'iming2': 32472,
 'sja': 73112,
 'kode': 39930,
 'semua': 71075,
 'kemarin2': 37766,
 'semenjak': 70922,
 'tv': 81938,
 'polytron': 64158,
 'salah': 68373,
 'seller': 70729,
 'begitu': 9787,
 'hubungi': 31675,
 'mesin': 50898,
 'bingung': 12445,
 'kritik': 40911,
 'costumer': 17040,
 'service': 71760,
 'butuh': 14929,
 '1x24jam': 796,
 'oren': 58259,
 'cair': 15211,
 'gaak': 26512,
 'kaleng²': 35792,
 'pengirimannya': 61487,
 'commers': 16797,
 'riwayat': 67474,
 'saldi': 68415,
 'bukanya': 14597,
 'manjain': 45493,
 'akunya': 4144,
 'batasi': 9269,
 'bye': 15046,
 'to': 79743,
 'pret': 64634,
 'maling': 45083,
 'potong': 64329,
 'tangan': 76266,
 'mas': 46691,
 'william': 84785,
 'siiipppp': 72641,
 'misalkan': 51397,
 '100perak': 191,
 'toggle': 79792,
 'ilangin': 32355,
 'beranda': 10426,
 'gratisan': 28950,
 'semoga': 70997,
 'commerce': 16792,
 'satu': 69146,
 'se': 69554,
 'indonesia': 32667,
 'raya': 66243,
 'dakla': 17770,
 'alias': 4431,
 'ruwet': 68032,
 'brang': 13859,
 'uangnya': 82073,
 'atm': 6934,
 'mala': 44979,
 'please': 63596,
 'si': 72407,
 'siput': 72956,
 'lambat': 42100,
 'kalaupun': 35768,
 'kerjasama': 38488,
 'untung': 82824,
 'tp': 80774,
 'doank': 22855,
 'lama2': 42025,
 'user': 83116,
 'kabur': 35526,
 'muda²han': 52883,
 'ne': 53960,
 'minyak': 51372,
 'kecil': 37071,
 'biaya': 12196,
 'layanan': 42490,
 'hapus': 30235,
 'scam': 69411,
 'pengirimananya': 61479,
 'terlalu': 78071,
 'sanpai': 68966,
 '6hr': 2159,
 'minta': 51327,
 'tokol': 79944,
 'malahan': 44992,
 'semuanya': 71092,
 'ampas': 4880,
 'paketan': 58912,
 'surabaya': 75296,
 'diberikan': 19422,
 'tolonggg': 80430,
 'saat': 68142,
 'ingin': 32782,
 'pickup': 63065,
 'bantuan': 8778,
 'nihil': 55624,
 'mohonnnnnnnnn': 52248,
 'kejelasannya': 37410,
 'sept': 71480,
 '2024': 865,
 'terletak': 78117,
 'daerah': 17650,
 'kacau': 35549,
 'disajikan': 21656,
 'berkualitas': 11032,
 'menemuka': 49135,
 'terhadap': 77717,
 'laen': 41803,
 'tadinya': 75884,
 'alasan': 4250,
 'sesuai': 71826,
 'adain': 3119,
 'alibi': 4435,
 'pakek': 58894,
 'lakok': 41973,
 'seakan2': 69575,
 'percuma': 62153,
 'balikin': 8238,
 'va': 83366,
 'gua': 29204,
 'kapan': 36095,
 'anjir': 5377,
 'cek': 15748,
 'gawat': 27318,
 'ni': 55548,
 'download': 23255,
 'pajak': 58821,
 'dicheck': 19661,
 'out': 58472,
 'katakan': 36416,
 'pelanggaran': 60177,
 'seharusnya': 70165,
 'dikatakan': 20356,
 'tu': 81645,
 'check': 16144,
 'transfer': 81014,
 'begini': 9771,
 'ambil': 4752,
 'mengendap': 49459,
 'merasa': 50685,
 'diberi': 19419,
 'harapan': 30276,
 'palsu': 59038,
 'narik': 53774,
 'lamanya': 42068,
 'ampun': 4921,
 'satset': 69137,
 'lacak': 41776,
 'beneran': 10271,
 'plis': 63652,
 'gps': 28852,
 'log': 43544,
 'dll': 22745,
 'dri': 23449,
 'pda': 59739,
 'bagusan': 7743,
 'pusing': 65595,
 'lokasi': 43611,
 'tempat': 77076,
 'kamu': 35980,
 'tulis': 81744,
 'nama': 53596,
 'ngarahnya': 54430,
 'orderan': 58231,
 'diproses': 21443,
 'alhasil': 4402,
 'sia': 72408,
 'persentase': 62604,
 'diselesaikannya': 21808,
 'bawah': 9341,
 '30': 1259,
 'tolonglah': 80441,
 'toko2': 79879,
 'kaya': 36537,
 'suspend': 75420,
 'org': 58274,
 'pertama': 62674,
 'lwt': 44210,
 'ngerampas': 54969,
 'lo': 43478,
 'haram': 30262,
 'anj': 5256,
 'emng': 24703,
 'omong': 57710,
 'lgsg': 43019,
 'gamau': 26904,
 'gopayleter': 28708,
 'dibuka': 19560,
 'cicilan': 16267,
 'bulan': 14647,
 'disuruh': 22118,
 'aktifkan': 4052,
 'gopaylater': 28694,
 'sdh': 69514,
 'aktif': 4041,
 'kebanyakkan': 36812,
 'criss': 17172,
 'cross': 17193,
 'nih': 55617,
 'lapak': 42343,
 'ku': 41103,
 'blacklist': 12793,
 'sameday': 68582,
 'dipilih': 21353,
 'apaan': 5698,
 'nahh': 53516,
 'peraturan': 62015,
 'kayaknya': 36546,
 'mendonglut': 49043,
 'dipisah': 21374,
 'pisah': 63346,
 'virtual': 83704,
 'bgt': 11978,
 'promo2': 64976,
 'klik': 39614,
 'white': 84695,
 'screen': 69468,
 'lancar': 42169,
 'jaya': 34118,
 'minimal': 51280,
 'boss': 13727,
 'ditumpuk': 22509,
 'secara': 69854,
 'pemilihan': 60816,
 'anda': 5041,
 'dimengerti': 20861,
 'sebanyak': 69661,
 'dua': 23672,
 'walaupun': 84238,
 'hasil': 30447,
 'ditambahkan': 22169,
 'berikutnya': 10830,
 'kedepannya': 37172,
 'kalian': 35800,
 'membuat': 48171,
 'seneng': 71216,
 'gmna': 28211,
 'sii': 72580,
 'sendiri': 71186,
 'efisien': 24279,
 'pass': 59501,
 'later': 42418,
 'masukin': 46882,
 'pin': 63229,
 'diganti': 19948,
 'tetep': 78783,
 'anehh': 5126,
 'kesel': 38684,
 'top': 80578,
 'terdepan': 77614,
 'koca': 39899,
 'maunya': 47116,
 'tpi': 80786,
 'tau2': 76582,
 'jossss': 35060,
 'buku': 14632,
 'bekas': 9858,
 'cenggo': 15840,
 'tahu': 75964,
 'sampe': 68653,
 'ntar': 56288,
 'memberikan': 48079,
 'ngasi': 54453,
 'gajls': 26801,
 'bru': 14199,
 'dikasi': 20341,
 'voc': 83772,
 'gmn': 28210,
 'gprnh': 28851,
 'ksi': 41006,
 'rate': 66200,
 'bener2': 10264,
 'gunain': 29333,
 'chekout': 16168,
 'adakan': 3125,
 'affiliate': 3423,
 'shope': 72286,
 'coba': 16589,
 'kendalanya': 37988,
 'loh': 43579,
 'bnget': 13126,
 'okeh': 57379,
 'ah': 3556,
 'kesalahan': 38603,
 'anteraja': 5539,
 'ngerti': 55025,
 ...}

In [ ]:
#kolom pertama ini berarti jumlah dokumen
#kolom kedua berarti letak katanya
#kolom ketiga hasil dari tf

term_frequency_all = term_fit.transform(Ulasan)
print (term_frequency_all)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3447619 stored elements and shape (500000, 88203)>
  Coords	Values
  (0, 44786)	1
  (0, 80599)	1
  (1, 6020)	1
  (1, 8827)	1
  (1, 19296)	1
  (1, 19340)	1
  (1, 20342)	1
  (1, 20517)	1
  (1, 34098)	1
  (1, 39784)	1
  (1, 62042)	1
  (1, 63034)	1
  (1, 64974)	1
  (1, 73015)	2
  (1, 74755)	2
  (1, 76431)	1
  (1, 80033)	1
  (1, 80424)	1
  (2, 45806)	1
  (3, 28455)	2
  (4, 3415)	1
  (4, 4119)	1
  (4, 4694)	1
  (4, 12984)	1
  (4, 14821)	1
  :	:
  (499995, 7734)	1
  (499995, 68818)	1
  (499996, 6020)	1
  (499996, 8827)	1
  (499996, 12571)	1
  (499996, 14439)	1
  (499996, 17824)	1
  (499996, 18608)	1
  (499996, 32821)	1
  (499996, 41918)	1
  (499996, 45344)	1
  (499996, 48179)	1
  (499996, 50068)	1
  (499996, 52825)	1
  (499996, 60391)	1
  (499996, 69213)	2
  (499996, 83079)	2
  (499996, 84821)	1
  (499996, 85837)	1
  (499997, 47960)	1
  (499997, 68818)	1
  (499998, 48580)	1
  (499998, 68818)	1
  (499999, 11156)	1
  (499999, 68818)	1

In [ ]:
ulasan_tf = Ulasan[1] #memanggil kata pada index ke 1
print (ulasan_tf)

Aplikasi php sudah banyak dikasih promo &sudah dibayar tapi diklik jawabnya dibatalkan sistem tolong perbaiki sistem kmu tokopedia

In [ ]:
term_frequency = term_fit.transform([ulasan_tf]) #hanya menampilkan hasil document 1
print (term_frequency)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 16 stored elements and shape (1, 88203)>
  Coords	Values
  (0, 6020)	1
  (0, 8827)	1
  (0, 19296)	1
  (0, 19340)	1
  (0, 20342)	1
  (0, 20517)	1
  (0, 34098)	1
  (0, 39784)	1
  (0, 62042)	1
  (0, 63034)	1
  (0, 64974)	1
  (0, 73015)	2
  (0, 74755)	2
  (0, 76431)	1
  (0, 80033)	1
  (0, 80424)	1

In [ ]:
dokumen = term_fit.transform(Ulasan) #hasil perhitungan tf idf dalam 1 doc
tfidf_transformer = TfidfTransformer().fit(dokumen)
print (tfidf_transformer.idf_)

tfidf=tfidf_transformer.transform(term_frequency)
print (tfidf) #hasil manual dengan sistem pyhton

[ 9.31834433  6.89761197 11.55741602 ... 13.02375309 12.73607102
 13.4292182 ]
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (1, 88203)>
  Coords	Values
  (0, 6020)	0.1307141172243781
  (0, 8827)	0.1485404961713671
  (0, 19296)	0.19026965724297082
  (0, 19340)	0.2574913392069116
  (0, 20342)	0.25385809524554065
  (0, 20517)	0.33072434294495817
  (0, 34098)	0.3117194713545378
  (0, 39784)	0.3679278428939415
  (0, 62042)	0.22466119746469615
  (0, 63034)	0.2661555717056662
  (0, 64974)	0.15832624738972093
  (0, 73015)	0.3734843185598679
  (0, 74755)	0.31721283418731916
  (0, 76431)	0.15489049305770156
  (0, 80033)	0.10668040582566933
  (0, 80424)	0.17354487479167777

# NLP

In [ ]:
data_label = data[["Nama_Produk", "Akun", "Ulasan_clean", "label"]]

In [ ]:
data_label["Ulasan_clean"] = data_label["Ulasan_clean"].fillna("tidak ada komentar")

In [ ]:
data_label.to_excel("data_label.xlsx")

In [ ]:
sentimen_data=pd.value_counts(data_label["label"], sort= True)
sentimen_data.plot(kind= 'bar', color= ["green", "red"])
plt.title('Bar chart')
plt.show()

Dapat dilihat bahwa isi ulasan produk lebih banyak pada label sentimen 1 atau ulasan dengan rating postitif ini berarti pelanggan yang menggunakan marketplace Tokopedia dan melakukan transaksi pembelian pada produk masker Kesehatan merasa puas bertansaksi di marketplace Tokopedia dan prosuk masker Kesehatan sehingga memberikan feedback atau ulasan komentar lebih banyak yang positif.

In [ ]:
from wordcloud import WordCloud

**Ulasan Negatif**

In [ ]:
train_s0 = data_label[data_label["label"] == 0]

In [ ]:
train_s0["Ulasan_clean"] = train_s0["Ulasan_clean"].fillna("tidak ada komentar")

In [ ]:
train_s0

In [ ]:
all_text_s0 = ' '.join(word for word in train_s0["Ulasan_clean"])
wordcloud = WordCloud(colormap='Reds', width=1000, height=1000, mode='RGBA', background_color='white').generate(all_text_s0)
plt.figure(figsize=(20,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

Dari visualisasi diatas merupakan wordcloud kata yang paling banyak muncul pada isi ulasan yang memiliki label sentimen negatif. Kata yang paling sering muncul dan mengarah ke ulasan negatif membahas seputar : barang, harga, kotak, penyok, box, dus, tipis, putus, sobek, kualitas, karet, bolong dan sebagainya. Sehingga dari kata-kata ini bisa menjadi masukan untuk penjual dan marketplace Tokopedia untuk meningkatkan kualitas barang (produk masker kesehatan), harga, kualitas pengiriman atau pengemasan, serta kualitas produk masker Kesehatan yang paling banyak disebutkan pelanggan dalam hasil Analisa ulasan sentimen yang negatif.

**Ulasan Positif**

In [ ]:
train_s1 = data_label[data_label["label"] == 1]

In [ ]:
train_s1["Ulasan_clean"] = train_s1["Ulasan_clean"].fillna("tidak ada komentar")

In [ ]:
train_s1

In [ ]:
all_text_s1 = ' '.join(word for word in train_s1["Ulasan_clean"])
wordcloud = WordCloud(colormap='Blues', width=1000, height=1000, mode='RGBA', background_color='white').generate(all_text_s1)
plt.figure(figsize=(20,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Ulasan Positif")
plt.margins(x=0, y=0)
plt.show()

Dari visualisasi diatas merupakan wordcloud kata yang paling banyak muncul pada ulasan yang memiliki label sentimen positif. Kata yang paling sering muncul dan mengarah ke ulasan positif membahas seputar : barang, cepat, bagus, masker, aman, kualitas, sesuai, rapi, respon, aman, recommended, dan sebagainya. Sehingga dari kata-kata ini bisa menjadi masukan untuk penjual dan marketplace Tokopedia untuk menjaga kualitas atau meningkatkan kembali kualitas barang (produk masker kesehatan), kualitas yang sesuai dan aman, serta respon penjual paling banyak disebutkan pelanggan dalam hasil Analisa ulasan sentimen yang positif.

# Menyiapkan Data Train dan Test

Pada proses ini kami menggunakan library sklearn.model_selection dengan modul train_test _split untuk membagi data latih (X_train dan y_train) dan data uji (X_test dan y_test) dengan persentasi data latih 70% dan data uji 30% serta memilih label data yaitu yang merupakan variable independen dari data kami yaitu kolom label untuk dijadikan parameter klasifikasi prediksi.

In [ ]:
data_label['Ulasan_clean'] = data_label['Ulasan_clean'].fillna("tidak ada komentar")

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_label['Ulasan_clean'], data_label['label'],
                                                    test_size=0.1, stratify=data_label['label'], random_state=30)

# TF-IDF

Pada proses ini kami menggunakan pembobotan TF-IDF(term frequency–inverse document) untuk menghitung manual dengan menggunakan python pembobotan kata dalam dokumen data ulasan.

In [ ]:
import numpy as np

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8')

In [ ]:
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train.shape)
print(X_test.shape)

In [ ]:
X_train = X_train.toarray()

In [ ]:
X_test = X_test.toarray()

# Machine Learning

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

#deklarasi metode cross validation
cv_method = RepeatedStratifiedKFold(n_splits=5,  n_repeats=3, random_state=999)
#tuning hyperparameter menggunakan gridsearch

params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gscv_nb = GridSearchCV(estimator=nb,
                 param_grid=params_NB,
                 cv=cv_method,   # use any cross validation technique
                 verbose=1,
                 scoring='accuracy')

#Fitting ke Model
gscv_nb.fit(X_train,y_train)
#mendapatkan hyperparameters terbaik
gscv_nb.best_params_

In [ ]:
nb = GaussianNB(var_smoothing=1.0)

In [ ]:
nb.fit(X_train, y_train)

In [ ]:
y_pred_nb = nb.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
print('--------------------- confusion matrix  ----------------------------')
print(confusion_matrix(y_test, y_pred_nb))
print('--------------------- classification report  ----------------------------')
print(classification_report(y_test, y_pred_nb))

Setelah dilakukan pembagian data latih dan data uji serta pembobotan tf-idf selanjutnya dapat dilakukan proses klasifikasi prediksi menggunakan model algoritma Naïve Bayes seperti proses yang ditunjukkan pada gambar 4. Didapatkan model algoritma Naïve Bayes dapat memberikan akurasi yang cukup baik sampari 88%.

> Dari hasil penelitian menggunakan Metode Algoritma Naïve Bayes untuk mengetahui sentimen ulasan pengguna dengan klasifikasi 2 kelas positif dan negative dengan pendekatan NLP menghasilkan nilai akurasi sebesar 88%. Selain itu, didapatkan bahwa Analisa Sentimen pada ulasan marketplace Tokopedia pada produk masker kesehatan menunjukan lebih banyak pada ulasan yang positif. Ini berarti pelayanan dan produk masker Kesehatan yang disediakan di marketplace Tokopedia sudah cukup baik.


> Dari hasil Analisis diatas dapat disimpulkan hasil scraping yang kami dapat dari produk pencarian masker kesehatan pada Tokopedia menampilkan data yang menunjukan ulasan positif lebih dominan daripada hasil ulasan negatif dan untuk ulasan negatif kata yang paling sering muncul adalah seputar kualitas produk yang tipis,mudah putus, sobek atau bolong, kualitas karetnya dan  pada pengemasan yaitu kotak/dus penyok dan untuk analisa positif kata yang paling sering muncul adalah seputar kualitas produk yang sesuai dan rapi, pengiriman yang aman dan cepat dan respon penjual.